// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmovKD7Pvp0SVTk_-2Oozf8Ye-0tAA3UU',
    appId: '1:102540313442:web:06acabd233b36ac04ba23b',
    messagingSenderId: '102540313442',
    projectId: 'karabaglarpersonelim',
    authDomain: 'karabaglarpersonelim.firebaseapp.com',
    storageBucket: 'karabaglarpersonelim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYL1TtPbA7a7-EWoqNng2NEmrDDsy_Sec',
    appId: '1:102540313442:android:de33cc344f625a284ba23b',
    messagingSenderId: '102540313442',
    projectId: 'karabaglarpersonelim',
    storageBucket: 'karabaglarpersonelim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_enfsUU-6KuiCT8NP4aQbpeNt26tNvrM',
    appId: '1:102540313442:ios:6b24dc4f226f9c7c4ba23b',
    messagingSenderId: '102540313442',
    projectId: 'karabaglarpersonelim',
    storageBucket: 'karabaglarpersonelim.appspot.com',
    androidClientId: '102540313442-j11k4a46mb5t63pqn39ldqujjb8utv6k.apps.googleusercontent.com',
    iosBundleId: 'com.karabaglar.karabaglarpersonelim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_enfsUU-6KuiCT8NP4aQbpeNt26tNvrM',
    appId: '1:102540313442:ios:101408777ac4e2114ba23b',
    messagingSenderId: '102540313442',
    projectId: 'karabaglarpersonelim',
    storageBucket: 'karabaglarpersonelim.appspot.com',
    androidClientId: '102540313442-j11k4a46mb5t63pqn39ldqujjb8utv6k.apps.googleusercontent.com',
    iosBundleId: 'com.izmirbb.prsUygulamasi.RunnerTests',
  );
}
